[package]
name = "dnslogger-forward"
version = "0.1.0"
authors = ["Stefan Bühler <buehler@cert.uni-stuttgart.de>"]

[dependencies]
clap = { version = "~2.19.2", features = ["unstable"] }
dnslogger-utils = { path = "dnslogger-utils" }
